name: Integration Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update packages
      run: sudo apt-get update
    
    - name: Install packages
      run: sudo apt-get install --fix-missing libgl1-mesa-dev libxext-dev

    - name: Configure CMake
      env:
        CC: clang
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build 

    - name: Build
      env:
        CC: clang
      run: cmake --build ${{github.workspace}}/build --parallel 
